<?php

namespace Application\Controllers;

use Application\Core\User;
use Phalcon\Mvc\View;
use Application\Models\Users;

class IndexController extends ControllerBase {
	public function beforeExecuteRoute($dispatcher)
    {
        parent::beforeExecuteRoute($dispatcher); // TODO: Change the autogenerated stub
    }

    public function helloWorldAction() {
		$this->view->disable();
		echo "Hello World";
    }

    public function indexAction() {
        $users = Users::find();
        $this->view->users = $users;
    }
    
    public function signupAction() {
        
    }
}

